---

# This Playbook would deploy everything
- hosts:
    - "duts"
  roles:
    - common
    - headless_raspi
    - { role: upgrade, when: upgrade_and_reboot is defined }
    - { role: reboot, when: upgrade_and_reboot is defined }
    - board_farm_git

- hosts: "*-networked"
  roles:
    - networked

- hosts: "*-lan"
  roles:
    - lan_device

- hosts: "*-wan"
  roles:
    - wan_device

- hosts: "*-controller"
  roles:
    - boardfarm_controller_git
    - jenkins_client
    - controller
