---
# This Playbook runs all the network plays in the deployment
- name: Install required packages for network testing computers
  apt: pkg={{item}} state=installed
  with_items:
    - openssh-client
    - tftp-hpa
    - tftpd-hpa
    - curl
    - socat
    - tinyproxy
    - iperf
  become: yes

- name: add tester group
  group:
    name: "{{item}}"
  become: yes
  with_items:
    - tester

- name: "Install experimenter user if not there"
  user:  #only accesssible via jump ssh so password doesn't matter
    name: "tester"
    password: "$6$n1V.7DrwPZ$8XgPr.NBUehriFL..bnGZrtJjfgv/V6yqSinpnBzMGTkcixWODFwTlA6eUaNqPnJIm1Y9AusY7IxocB6cJHLj0" #should be 'test'
    groups: "tester"
  become: yes

- name: create testing_cmds alias in sudo
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^Cmnd_Alias TESTING_CMDS'
    line: 'Cmnd_Alias TESTING_CMDS = /sbin/reboot, /usr/bin/start_lan_client, /usr/bin/ip_neigh_flush, /usr/bin/turn_on_pppoe, /usr/bin/restart_tftp_server, /usr/bin/stop_lan_client'
    validate: 'visudo -cf %s'
  become: yes

- name: give user access to testing_cmds in sudo
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^tester ALL'
    line: 'tester ALL=(ALL) NOPASSWD: TESTING_CMDS'
    validate: 'visudo -cf %s'
  become: yes
