---
- name: pull in boardfarm
  git:
    repo: "{{ boardfarm_repo }}"
    version: "{{ boardfarm_repo_branch}}"
    dest: /opt/boardfarm
    force: yes
  become: yes

- name: "install requirements for boardfarm"
  pip:
    requirements: "requirements.txt"
    state: present
    chdir: /opt/boardfarm
  become: yes
